### ISSUE TITLE
Why not publish this?

### ISSUE THREAD

**Issue by occultus73** [qwwdfsad/kotlinx-fs#2]
This looks brilliant. I need to use this concurrently with Kotlinx IO to read and write bytes to a files in a multiplatform project.

**Comment by qwwdfsad** [comment]
This was just an experiment never aiming to be production-ready, unfortunately.
I suggest you taking look at the Okio project that provides capabilities you are looking for

**Comment by occultus73** [comment]
Multiplatform man. I need a Multiplatform file system io library. It's a glaring hole in the kotlinx suite of pure kotlin libraries. Surely this is on JetBrains radar right? The success of the Kotlin Multiplatform hinges on the completeness of kotlinx.

Edit: I see the file IO part of Okio apparently is multiplatform. I did not know this. Let me check that out.
https://square.github.io/okio/multiplatform/

**Comment by qwwdfsad** [comment]
Okio is indeed multiplatform and we are happy that other companies are shipping high-quality MPP libraries. Eventually, we cannot cover every potentially useful set of API with `kotlinx.*` libraries, but it is possible with a diverse community of library authors
